"""add note to deployment tests

Revision ID: 2421397b68ae
Revises: 324e369d0d2a
Create Date: 2026-08-29 23:02:07.273358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2421397b68ae'
down_revision: Union[str, Sequence[str], None] = '324e369d0d2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deployment_tests', sa.Column('note', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deployment_tests', 'note')
    # ### end Alembic commands ###
